name: Workflow Dispatch

on:
  workflow_dispatch:

env:
  VERSION: 0.0.2

jobs:
  Build-test-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
         dotnet-version: '7.0.x'
         dotnet-quality: 'preview'
         
    - name: Publish launcher
      run: dotnet publish DatafusLibrary.Launcher/DatafusLibrary.Launcher.csproj -c Release -f net7.0 -r linux-x64 --self-contained false

    - name: Run launcher
      run: dotnet DatafusLibrary.Launcher/bin/Release/net7.0/linux-x64/DatafusLibrary.Launcher.dll

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "/home/runner/work/DatafusLibrary/DatafusLibrary/DatafusLibrary.SourceGenerators.Tests/bin/Debug/net7.0_release.zip"

    - name: Publish release
      if: steps.check_files.outputs.files_exists == 'true' 
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.VERSION }}
        prerelease: false
        title: ${{ env.VERSION }}
        files: "/home/runner/work/DatafusLibrary/DatafusLibrary/DatafusLibrary.SourceGenerators.Tests/bin/Debug/net7.0_release.zip"