name: Workflow Dispatch

on:
  workflow_dispatch:
  #push:
    #branches:
      #- master

env:
  VERSION: 0.0.1

jobs:
  Build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
         dotnet-version: '7.0.x'
         dotnet-quality: 'preview'
         
    - name: Restore packages
      run: dotnet restore

    - name: Build launcher
      run: dotnet build DatafusLibrary.Launcher.csproj --configuration Release --no-restore --verbosity normal
    
    - name: Run launcher
      run: DatafusLibrary.Launcher.exe

  Publish:
     runs-on: ubuntu-latest
     needs: Build-and-test
     
     steps:
     - name: Publish release
       uses: "marvinpinto/action-automatic-releases@latest"
       with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: ${{ env.VERSION }}
         prerelease: false
         title: ${{ env.VERSION }}
         files: |
          ./release.zip