name: Workflow Dispatch

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master

env:
  VERSION: 0.0.2

jobs:
  Build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
         dotnet-version: '7.0.x'
         dotnet-quality: 'preview'
         
    - name: Restore packages
      run: dotnet restore DatafusLibrary.Launcher/DatafusLibrary.Launcher.csproj

    #- name: Build launcher
    #  run: dotnet build DatafusLibrary.Launcher/DatafusLibrary.Launcher.csproj --configuration Release --no-restore --verbosity normal
    
    - name: Publish launcher
      run: dotnet publish DatafusLibrary.Launcher/DatafusLibrary.Launcher.csproj -c Release -f net7.0 -r linux-x64 --self-contained false --no-restore

    - name: Run launcher
      run: dotnet DatafusLibrary.Launcher/bin/Release/net7.0/linux-x64/DatafusLibrary.Launcher.dll

  Publish:
     runs-on: ubuntu-latest
     needs: Build-and-test

     steps:
     - name: Check file existence
       id: check_files
       uses: andstor/file-existence-action@v2
       with:
         files: "${{ env.GITHUB_WORKSPACE }}/DatafusLibrary.SourceGenerators.Tests/bin/Debug/net7.0_release.zip"

     - name: File exists annouce
       if: steps.check_files.outputs.files_exists == 'true'
       run: echo "Release archive exists!"

     - name: Publish release
       if: steps.check_files.conclusion == success 
       uses: "marvinpinto/action-automatic-releases@latest"
       with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: ${{ env.VERSION }}
         prerelease: false
         title: ${{ env.VERSION }}
         files: |
          "${{ env.GITHUB_WORKSPACE }}/DatafusLibrary.SourceGenerators.Tests/bin/Debug/net7.0_release.zip"